### ISSUE TITLE
Game crashes when I try to use the respawn beacon when I shift-right click on it

### ISSUE THREAD

**Issue by Hellodarkknight1507** [ApacheTech-VintageStory-Mods/RespawnTools#1]
**Describe the Bug:**
I'm playing in 1.19.8 in a survival standard game and it crashes when I when I shift-right click on the respawn beacon

**To Reproduce:**
Just try to shift-right click on the respawn beacon

**Expected Behaviour:**
When you try to use the respawn beacon it supposed to do the follow instructions
-Client: Shift-Right Click to toggle the settings window for the beacon.
-Change the range of the beacon. Defaults to 128 blocks.
-Turn the beacon on or off.

**Comment by ApacheTech** [comment]
Fixed in v1.3.2

**Comment by Hellodarkknight1507** [comment]
It still doesn't work/

**Comment by ApacheTech** [comment]
I will need all your log files. Log into the game, make it crash, and then zip your entire logs folder, and drag and drop onto here to upload it.

**Comment by Hellodarkknight1507** [comment]
Sure, there you go
[Logs.zip](https://github.com/user-attachments/files/16934297/Logs.zip)

**Comment by ApacheTech** [comment]
I didn't have a language file for LatAm Spanish. Fixing now. :)

**Comment by ApacheTech** [comment]
También estoy aprendiendo español latinoamericano. Es típico que es el que no tengo.

**Comment by Hellodarkknight1507** [comment]
Jajaja, no te preocupes, aprecio que te tomes el tiempo 
Me parece un mod genial

**Comment by ApacheTech** [comment]
Muchos gracias

**Comment by ApacheTech** [comment]
Fixed (hopefully) in v1.3.3

**Comment by ApacheTech** [comment]
Just realised that may not have fixed it. Let me know how it goes.

**Comment by ApacheTech** [comment]
Now fixed, in v1.3.4

**Comment by Hellodarkknight1507** [comment]
Thanks:)
I'll check it
And I if you want to learn more Spanish I have a Twitch account where I play VS and chat with the viewers:)
Let you the link if you want to take a look
www.twitch.tv/dark_knight_ll
